"use client"

import type React from "react"

import { createContext, useContext, useState, useEffect } from "react"

export type Language = "en" | "es" | "zh" | "hi" | "ar"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

export const translations: {
  en: { [key: string]: string },
  es: { [key: string]: string },
  zh: { [key: string]: string },
  hi: { [key: string]: string },
  ar: { [key: string]: string }
} = {
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.upload": "Upload Lease",
    "nav.community": "Community",
    "nav.resources": "Resources",
    "nav.alerts": "Alerts",
    "nav.support": "Support",

    // Homepage
    "home.aiAssistant": "AI Assistant",
    "home.community": "Community",
    "home.resources": "Resources",
    "home.payment": "Payment",
    "home.alerts": "Alerts",
    "home.support": "Support",
    "home.youSelected": "You selected",
    "home.hero.title": "Understand your lease in plain English",
    "home.hero.subtitle": "Upload your lease document and get an AI-powered summary that breaks down complex legal terms into simple, understandable language.",
    "home.hero.cta": "Upload Lease",
    "home.askAIAssistant": "Ask AI Assistant",
    "how.title": "How it works",
    "how.step1": "Upload",
    "how.step1.desc": "Simply upload your lease document in PDF format. Our secure system processes it instantly.",
    "how.step2": "AI Summary",
    "how.step2.desc":
      "Our AI analyzes your lease and creates a clear, concise summary of the key terms and conditions.",
    "how.step3": "Unlock Full Breakdown",
    "how.step3.desc": "Get detailed explanations of complex clauses, potential red flags, and important dates.",

    // Community
    "community.title": "Renter Support Community",
    "community.subtitle":
      "Get help from fellow renters and housing experts. Ask questions anonymously and share your experiences.",
    "community.ask": "Ask a Question",
    "community.browse": "Browse Questions",
    "community.experts": "Expert Answers",
    "community.category.all": "All Categories",
    "community.category.rentIncreases": "Rent Increases",
    "community.category.securityDeposits": "Security Deposits",
    "community.category.repairsMaintenance": "Repairs & Maintenance",
    "community.category.neighborIssues": "Neighbor Issues",
    "community.category.leaseTerms": "Lease Terms",
    "community.category.eviction": "Eviction",
    "community.category.discrimination": "Discrimination",
    "community.category.utilities": "Utilities",
    "community.category.movingOut": "Moving Out",
    "community.category.other": "Other",
    "community.location.all": "All Locations",
    "community.location.california": "California",
    "community.location.texas": "Texas",
    "community.location.newYork": "New York",
    "community.location.florida": "Florida",
    "community.location.illinois": "Illinois",

    // Common
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.delete": "Delete",
    "common.edit": "Edit",

    // Upload
    "upload.formatError": "Please upload a PDF or image file (JPG, PNG, PDF)",
    "upload.fileSizeError": "File size must be less than 10MB. Try compressing your file or taking a clearer photo.",
    "upload.uploadError": "Something went wrong while processing your lease. Please try again.",
    "upload.backToHome": "Back to home",
    "upload.leaseEasy": "Conmates",
    "upload.uploadYourLease": "Upload Your Lease",
    "upload.uploadInstructions": "Upload your lease document and we'll break it down into simple, easy-to-understand terms.",
    "upload.analysisComplete": "Analysis Complete!",
    "upload.analysisSuccess": "We've successfully analyzed your lease. Here's what we found:",
    "upload.viewLeaseSummary": "View Your Lease Summary",

    // Support
    "support.describeSituation": "Describe your housing situation or question...",
    "support.backToHome": "Back to home",
    "support.humanSupport": "Human Support",
    "support.getHumanSupport": "Get Human Support",
    "support.connectWithExperts": "Connect with housing experts, counselors, and advocates who understand your situation and can provide personalized help.",
    "support.facingEmergency": "Facing an Emergency?",

    // Resources
    "resources.searchPlaceholder": "Search resources, organizations, or topics...",
    "resources.tenantRightsCA": "Comprehensive guide to tenant rights in California, including rent control, eviction protection, and habitability standards.",
    "resources.rentStabilizationNY": "Understanding rent stabilization and rent control laws in New York City and state.",
    "resources.tenantRightsTX": "Key sections of Texas Property Code that protect tenant rights and outline landlord obligations.",
    "resources.repairRequestTemplate": "Formal letter template to request repairs from your landlord with proper legal language.",
    "resources.securityDepositTemplate": "Template to demand return of security deposit with legal citations and deadlines.",
    "resources.allStates": "All States",
    "resources.california": "California",
    "resources.newYork": "New York",
    "resources.texas": "Texas",
    "resources.florida": "Florida",
    "resources.illinois": "Illinois",

    // Breakdown Page
    "breakdown.analysisTailored": "Analysis tailored for:",
    "breakdown.stateSpecificRules": "State-Specific Lease Rules & Tips",
    "breakdown.securityDepositLimit": "Security Deposit Limit",
    "breakdown.lateFeeLimit": "Late Fee Limit",
    "breakdown.noticePeriod": "Notice Period",
    "breakdown.requiredDisclosures": "Required Disclosures",
    "breakdown.tip": "Tip",
    "breakdown.backToSummary": "Back to Summary",
    "breakdown.leaseEasy": "Conmates",
    "breakdown.conmates": "Conmates",
    "breakdown.completeLeaseBreakdown": "Complete Lease Breakdown",
    "breakdown.leaseExplained": "Your lease, explained in plain English.",
    "breakdown.clauseByClause": "Clause-by-Clause",
    "breakdown.redFlags": "Red Flags",
    "breakdown.actionableTips": "Actionable Tips",
    "breakdown.understandingYourLease": "Understanding Your Lease",
    "breakdown.originalLeaseText": "Original Lease Text",
    "breakdown.whatThisMeans": "What This Means",
    "breakdown.proTips": "💡 Pro Tips",
    "breakdown.potentialRedFlags": "Potential Red Flags",
    "breakdown.impactOnYou": "Impact on You",
    "breakdown.whatYouCanDo": "What You Can Do",
    "breakdown.yourActionPlan": "Your Action Plan",
    "breakdown.shareYourFeedback": "Share Your Feedback",
    "breakdown.howHelpful": "How helpful was this analysis?",
    "breakdown.commentsOptional": "Comments (optional)",
    "breakdown.whatDidYouFindMostHelpful": "What did you find most helpful? What could we improve?",
    "breakdown.emailOptional": "Email (optional)",
    "breakdown.yourEmail": "your@email.com",
    "breakdown.emailPrivacy": "We'll only use this to follow up on your feedback if needed.",
    "breakdown.sending": "Sending...",
    "breakdown.sendFeedback": "Send Feedback",

    // Support Page (Support Options)
    "support.liveChatSupport": "Live Chat Support",
    "support.getInstantHelp": "Get instant help from our housing counselors",
    "support.phoneConsultation": "Phone Consultation",
    "support.speakWithExpert": "Speak directly with a housing expert",
    "support.videoConsultation": "Video Consultation",
    "support.faceToFaceHelp": "Face-to-face help with document review",
    "support.emergencyHotline": "Emergency Hotline",
    "support.urgentHousingIssues": "Urgent housing issues and eviction notices",

    // Breakdown Clauses
    "breakdown.clause.rent.title": "Monthly Rent & Payment Terms",
    "breakdown.clause.rent.section": "Section 3: Rent",
    "breakdown.clause.rent.originalText": "Tenant agrees to pay rent in the amount of $2,400.00 per month, due on the first day of each month. Late fees of $75.00 will be assessed for payments received after the 5th day of the month.",
    "breakdown.clause.rent.explanation": "You'll pay $2,400 every month, and it's due on the 1st. If you're late (after the 5th), you'll be charged a $75 late fee. This is pretty standard, but the late fee is on the higher side.",
    "breakdown.clause.rent.tip1": "Set up automatic payments to avoid the $75 late fee",
    "breakdown.clause.rent.tip2": "The 5-day grace period is reasonable - use it if needed",
    "breakdown.clause.rent.tip3": "Consider negotiating a lower late fee if you have good credit",
    "breakdown.clause.deposit.title": "Security Deposit",
    "breakdown.clause.deposit.section": "Section 4: Security Deposit",
    "breakdown.clause.deposit.originalText": "Tenant shall deposit with Landlord the sum of $2,400.00 as security for the faithful performance of Tenant's obligations. This deposit may be used to cover unpaid rent, damages beyond normal wear and tear, or cleaning costs.",
    "breakdown.clause.deposit.explanation": "You're putting down $2,400 as a security deposit (same as one month's rent). This money protects the landlord if you damage the place, don't pay rent, or leave it messy. You should get most or all of it back if you take good care of the apartment.",
    "breakdown.clause.deposit.tip1": "Document the apartment's condition when you move in with photos",
    "breakdown.clause.deposit.tip2": "Keep receipts for any improvements or repairs you make",
    "breakdown.clause.deposit.tip3": "Give proper notice when moving out to ensure deposit return",
    "breakdown.clause.term.title": "Lease Duration & Renewal",
    "breakdown.clause.term.section": "Section 2: Term",
    "breakdown.clause.term.originalText": "This lease shall commence on January 1, 2024, and terminate on December 31, 2024. Tenant may renew for additional one-year terms with 60 days written notice and Landlord's consent.",
    "breakdown.clause.term.explanation": "Your lease runs for exactly one year, from January 1st to December 31st, 2024. If you want to stay longer, you need to tell your landlord in writing at least 60 days before the lease ends, but they don't have to say yes.",
    "breakdown.clause.term.tip1": "Mark your calendar for November 1st to start renewal discussions",
    "breakdown.clause.term.tip2": "Start looking for alternatives early if renewal isn't guaranteed",
    "breakdown.clause.term.tip3": "Ask about renewal terms and potential rent increases upfront",
    "breakdown.clause.maintenance.title": "Maintenance & Repairs",
    "breakdown.clause.maintenance.section": "Section 8: Maintenance",
    "breakdown.clause.maintenance.originalText": "Landlord shall maintain the premises in habitable condition. Tenant is responsible for minor repairs under $100 and must report major issues within 48 hours of discovery.",
    "breakdown.clause.maintenance.explanation": "Your landlord has to keep the place livable (working heat, plumbing, etc.), but you're responsible for small fixes under $100. If something major breaks, you need to tell them within 2 days or you might be held responsible.",
    "breakdown.clause.maintenance.tip1": "Report issues immediately via email to create a paper trail",
    "breakdown.clause.maintenance.tip2": "Keep receipts for any repairs you make under $100",
    "breakdown.clause.maintenance.tip3": "Know what counts as 'habitable' - heat, water, electricity, safe structure",
    "breakdown.clause.pets.title": "Pet Policy",
    "breakdown.clause.pets.section": "Section 12: Pets",
    "breakdown.clause.pets.originalText": "No pets, animals, or livestock of any kind are permitted on the premises without prior written consent of Landlord, which may be withheld at Landlord's sole discretion.",
    "breakdown.clause.pets.explanation": "No pets allowed, period. Even if you ask nicely, your landlord can say no for any reason. This includes everything from dogs and cats to fish and hamsters.",
    "breakdown.clause.pets.tip1": "If you need a service animal, know your rights under the ADA",
    "breakdown.clause.pets.tip2": "Consider this carefully if you might want a pet during your lease",
    "breakdown.clause.pets.tip3": "Ask about pet policies before signing if this matters to you",
    "breakdown.clause.subletting.title": "Subletting & Assignment",
    "breakdown.clause.subletting.section": "Section 15: Assignment",
    "breakdown.clause.subletting.originalText": "Tenant may not assign this lease or sublet the premises, in whole or in part, without the prior written consent of Landlord. Any unauthorized assignment or subletting shall be grounds for immediate termination.",
    "breakdown.clause.subletting.explanation": "You can't let someone else live there or take over your lease without your landlord's written permission. If you do it anyway, they can kick you out immediately. This limits your flexibility if your situation changes.",
    "breakdown.clause.subletting.tip1": "Discuss subletting policies upfront if you might need flexibility",
    "breakdown.clause.subletting.tip2": "Get any subletting agreements in writing",
    "breakdown.clause.subletting.tip3": "Consider negotiating more flexible terms if you travel frequently",
    // Breakdown Red Flags
    "breakdown.redflag.noPetPolicy.title": "Strict No-Pet Policy",
    "breakdown.redflag.noPetPolicy.description": "The lease completely prohibits pets without any exceptions, which could be problematic if your circumstances change.",
    "breakdown.redflag.noPetPolicy.impact": "This inflexibility could force you to choose between your living situation and a pet, even for emotional support animals.",
    "breakdown.redflag.noPetPolicy.action": "Consider negotiating pet terms upfront or look for pet-friendly alternatives if this matters to you.",
    "breakdown.redflag.noSubletting.title": "No Subletting Rights",
    "breakdown.redflag.noSubletting.description": "You cannot sublet or assign your lease under any circumstances without landlord approval, which they can deny for any reason.",
    "breakdown.redflag.noSubletting.impact": "If you need to move early for work, family, or financial reasons, you'll be stuck paying rent for an empty apartment.",
    "breakdown.redflag.noSubletting.action": "Negotiate subletting rights or early termination clauses before signing.",
    "breakdown.redflag.highLateFee.title": "High Late Fee",
    "breakdown.redflag.highLateFee.description": "The $75 late fee is above average for this rent amount (typically 3-5% of monthly rent).",
    "breakdown.redflag.highLateFee.impact": "One late payment could cost you $75, which adds up quickly if you're occasionally late.",
    "breakdown.redflag.highLateFee.action": "Set up automatic payments and negotiate a lower late fee if possible.",
    "breakdown.redflag.tenantRepairs.title": "Tenant Responsible for Minor Repairs",
    "breakdown.redflag.tenantRepairs.description": "You're responsible for all repairs under $100, which could add up over time.",
    "breakdown.redflag.tenantRepairs.impact": "Small repairs like clogged drains, light fixtures, or cabinet handles become your expense.",
    "breakdown.redflag.tenantRepairs.action": "Budget for minor repairs and document all maintenance issues when you move in.",
    // Breakdown Actionable Tips
    "breakdown.tips.beforeSign.category": "Before You Sign",
    "breakdown.tips.beforeSign.tip1": "Take detailed photos/videos of the apartment's condition",
    "breakdown.tips.beforeSign.tip2": "Test all appliances, faucets, lights, and outlets",
    "breakdown.tips.beforeSign.tip3": "Ask about the landlord's typical response time for repairs",
    "breakdown.tips.beforeSign.tip4": "Clarify what 'normal wear and tear' means to avoid deposit disputes",
    "breakdown.tips.beforeSign.tip5": "Get all verbal promises in writing as lease addendums",
    "breakdown.tips.financialProtection.category": "Financial Protection",
    "breakdown.tips.financialProtection.tip1": "Set up automatic rent payments to avoid the $75 late fee",
    "breakdown.tips.financialProtection.tip2": "Budget an extra $50-100/month for minor repairs you'll be responsible for",
    "breakdown.tips.financialProtection.tip3": "Keep your security deposit in a separate savings account mentally",
    "breakdown.tips.financialProtection.tip4": "Document any improvements you make with receipts",
    "breakdown.tips.financialProtection.tip5": "Consider renter's insurance to protect your belongings",
    "breakdown.tips.duringLease.category": "During Your Lease",
    "breakdown.tips.duringLease.tip1": "Report maintenance issues immediately via email for paper trail",
    "breakdown.tips.duringLease.tip2": "Pay rent on time every month - late fees add up quickly",
    "breakdown.tips.duringLease.tip3": "Keep copies of all communications with your landlord",
    "breakdown.tips.duringLease.tip4": "Take photos before and after any repairs you make",
    "breakdown.tips.duringLease.tip5": "Be a good neighbor to maintain positive landlord relationship",
    "breakdown.tips.planningExit.category": "Planning Your Exit",
    "breakdown.tips.planningExit.tip1": "Mark November 1st on your calendar to discuss renewal",
    "breakdown.tips.planningExit.tip2": "Start planning 90 days before lease end if you're not renewing",
    "breakdown.tips.planningExit.tip3": "Clean thoroughly and repair any damage before move-out inspection",
    "breakdown.tips.planningExit.tip4": "Provide proper written notice as required by your lease",
    "breakdown.tips.planningExit.tip5": "Do a final walkthrough with your landlord and get it documented",
    // Resources Page (expanded i18n)
    "resources.backToHome": "Back to home",
    "resources.legalResources": "Legal Resources",
    // Tenant Rights Titles & Topics
    "resources.tenantRightsCA.title": "California Tenant Rights Guide",
    "resources.tenantRightsCA.topic1": "Rent Control",
    "resources.tenantRightsCA.topic2": "Eviction Protection",
    "resources.tenantRightsCA.topic3": "Security Deposits",
    "resources.tenantRightsCA.topic4": "Repairs & Maintenance",
    "resources.rentStabilizationNY.title": "New York Rent Stabilization Laws",
    "resources.rentStabilizationNY.topic1": "Rent Stabilization",
    "resources.rentStabilizationNY.topic2": "Lease Renewals",
    "resources.rentStabilizationNY.topic3": "Rent Increases",
    "resources.rentStabilizationNY.topic4": "Tenant Rights",
    "resources.tenantRightsTX.title": "Texas Property Code for Tenants",
    "resources.tenantRightsTX.topic1": "Security Deposits",
    "resources.tenantRightsTX.topic2": "Repairs",
    "resources.tenantRightsTX.topic3": "Notice Requirements",
    "resources.tenantRightsTX.topic4": "Discrimination",
    // Legal Aid Orgs
    "resources.lafla.name": "Legal Aid Foundation of Los Angeles",
    "resources.lafla.city": "Los Angeles",
    "resources.lafla.service1": "Eviction Defense",
    "resources.lafla.service2": "Housing Discrimination",
    "resources.lafla.service3": "Tenant Rights",
    "resources.lafla.eligibility": "Low-income residents of LA County",
    "resources.lasnyc.name": "Legal Aid Society of NYC",
    "resources.lasnyc.city": "New York",
    "resources.lasnyc.service1": "Housing Court Representation",
    "resources.lasnyc.service2": "Rent Stabilization",
    "resources.lasnyc.service3": "NYCHA Issues",
    "resources.lasnyc.eligibility": "Low-income NYC residents",
    "resources.lonestar.name": "Lone Star Legal Aid",
    "resources.lonestar.city": "Houston",
    "resources.lonestar.service1": "Eviction Prevention",
    "resources.lonestar.service2": "Fair Housing",
    "resources.lonestar.service3": "Landlord-Tenant Disputes",
    "resources.lonestar.eligibility": "Low-income Texas residents",
    // Languages
    "resources.language.english": "English",
    "resources.language.spanish": "Spanish",
    "resources.language.chinese": "Chinese",
    "resources.language.arabic": "Arabic",
    "resources.language.creole": "Creole",
    "resources.language.polish": "Polish",
    // Template Letters
    "resources.template.repairRequest.title": "Repair Request Letter",
    "resources.template.depositDemand.title": "Security Deposit Demand Letter",
    "resources.template.rentChallenge.title": "Rent Increase Challenge Letter",
    "resources.template.rentChallenge.description": "Template to challenge illegal rent increases with proper legal references.",
    "resources.template.habitabilityComplaint.title": "Habitability Complaint Letter",
    "resources.template.habitabilityComplaint.description": "Formal complaint template for uninhabitable conditions with health and safety violations.",
    // Quick Reference
    "resources.quickref.rights.title": "Know Your Rights Checklist",
    "resources.quickref.rights.item1": "Right to habitable living conditions",
    "resources.quickref.rights.item2": "Right to privacy (24-hour notice for entry)",
    "resources.quickref.rights.item3": "Right to return of security deposit",
    "resources.quickref.rights.item4": "Right to be free from discrimination",
    "resources.quickref.rights.item5": "Right to organize with other tenants",
    "resources.quickref.redflags.title": "Red Flags in Leases",
    "resources.quickref.redflags.item1": "Waiver of tenant rights",
    "resources.quickref.redflags.item2": "Excessive late fees (>5% of rent)",
    "resources.quickref.redflags.item3": "No repair timeline specified",
    "resources.quickref.redflags.item4": "Automatic rent increases without limits",
    "resources.quickref.redflags.item5": "Broad eviction clauses",
    "resources.quickref.emergency.title": "Emergency Contacts",
    "resources.quickref.emergency.item1": "Local housing authority",
    "resources.quickref.emergency.item2": "Tenant rights hotline",
    "resources.quickref.emergency.item3": "Legal aid organizations",
    "resources.quickref.emergency.item4": "Fair housing agencies",
    "resources.quickref.emergency.item5": "Emergency repair services",
    // Homepage (expanded i18n)
    "home.leaseEasy": "Conmates",
    "home.meetAIAssistant": "Meet Your AI Assistant",
    "home.poweredByGPT4": "Powered by GPT-4",
    "home.aiAssistantDescription": "Get instant, intelligent help 24/7. Our AI assistant understands lease agreements, tenant rights, and can guide you through any rental situation.",
    "home.leaseAnalysis": "Lease Analysis",
    "home.leaseAnalysisDesc": "Upload your lease and get instant explanations of complex terms and clauses.",
    "home.realTimeChat": "Real-time Chat",
    "home.realTimeChatDesc": "Ask questions and get immediate, contextual responses about your rental situation.",
    "home.legalGuidance": "Legal Guidance",
    "home.legalGuidanceDesc": "Learn about tenant rights and get guidance on handling rental disputes.",
    "home.startChattingNow": "Start Chatting Now",
    "home.completeSupportEcosystem": "Complete Renter Support Ecosystem",
    "home.communitySupport": "Community Support",
    "home.communitySupportDesc": "Get help from fellow renters and housing experts in our anonymous Q&A forum.",
    "home.legalResources": "Legal Resources",
    "home.legalResourcesDesc": "Access state-specific tenant rights guides and legal aid organizations.",
    "home.smartAlerts": "Smart Alerts",
    "home.smartAlertsDesc": "Never miss important lease deadlines with proactive notifications.",
    "home.humanSupport": "Human Support",
    "home.humanSupportDesc": "Connect with housing counselors and get personalized help.",
    "home.readyToUnderstand": "Ready to understand your lease?",
    "home.readyToUnderstandDesc": "Join thousands of renters who have simplified their lease understanding with Conmates.",
    "home.getStartedNow": "Get Started Now",
    "home.tryAIAssistant": "Try AI Assistant",
    "home.footerDesc": "Making lease agreements simple and understandable for everyone. Powered by AI, designed for clarity.",
    "home.platform": "Platform",
    "home.legal": "Legal",
    "home.privacyPolicy": "Privacy Policy",
    "home.termsOfService": "Terms of Service",
    "home.about": "About",
    "home.contact": "Contact",
    "home.copyright": "© 2024 Conmates. All rights reserved.",
    // Payment page translations
    "payment.completeYourPurchase": "Complete Your Purchase",
    "payment.securePayment": "Secure Payment",
    "payment.leaseAnalysis": "Lease Analysis",
    "payment.instantAccess": "Instant Access",
    "payment.oneTimePayment": "One-time payment",
    "payment.whatsIncluded": "What's Included",
    "payment.aiAnalysis": "AI-powered lease analysis",
    "payment.clauseBreakdown": "Clause-by-clause breakdown",
    "payment.redFlagDetection": "Red flag detection",
    "payment.pdfReport": "PDF report download",
    "payment.communityAccess": "Community access",
    "payment.emailAddress": "Email Address",
    "payment.enterEmail": "Enter your email",
    "payment.fullName": "Full Name",
    "payment.enterName": "Enter your full name",
    "payment.processing": "Processing...",
    "payment.payNow": "Pay Now",
    "payment.stripeSecurity": "Your payment is secure, and we never store your financial data. All transactions are processed through Stripe's secure servers.",


    // Payment success page translations
    "payment.success.title": "Payment Successful!",
    "payment.success.description": "Thank you for your purchase. You now have access to Conmates's full features.",
    "payment.success.orderDetails": "Order Details",
    "payment.success.product": "Product",
    "payment.success.amount": "Amount",
    "payment.success.status": "Status",
    "payment.success.paid": "Paid",
    "payment.success.transactionId": "Transaction ID",
    "payment.success.nextSteps": "Next Steps",
    "payment.success.step1.title": "Upload Your Lease",
    "payment.success.step1.description": "Go to the upload page and submit your lease document for analysis.",
    "payment.success.step2.title": "Get Your Analysis",
    "payment.success.step2.description": "Receive a comprehensive breakdown of your lease terms and conditions.",
    "payment.success.step3.title": "Download Report",
    "payment.success.step3.description": "Download your detailed PDF report for future reference.",
    "payment.success.uploadLease": "Upload Lease",
    "payment.success.goToDashboard": "Go to Dashboard",
    "payment.success.securityTitle": "Secure Transaction",
    "payment.success.securityDescription": "Your payment has been processed securely through Stripe. You will receive a confirmation email shortly.",
    "payment.success.needHelp": "Need help getting started?",
    "payment.success.contactSupport": "Contact Support",
  },
  es: {
    // Navigation
    "nav.home": "Inicio",
    "nav.upload": "Subir Contrato",
    "nav.community": "Comunidad",
    "nav.resources": "Recursos",
    "nav.alerts": "Alertas",
    "nav.support": "Soporte",

    // Homepage
    "home.aiAssistant": "AI Assistant",
    "home.community": "Comunidad",
    "home.resources": "Recursos",
    "home.payment": "Pago",
    "home.alerts": "Alertas",
    "home.support": "Soporte",
    "home.youSelected": "Usted seleccionó",
    "home.hero.title": "Entiende tu contrato de alquiler en español simple",
    "home.hero.subtitle":
      "Sube tu documento de contrato y obtén un resumen impulsado por IA que desglosa términos legales complejos en un lenguaje simple y comprensible.",
    "home.hero.cta": "Subir Contrato",
    "home.askAIAssistant": "Preguntar a AI Assistant",
    "how.title": "Cómo funciona",
    "how.step1": "Subir",
    "how.step1.desc":
      "Simplemente sube tu documento de contrato en formato PDF. Nuestro sistema seguro lo procesa instantáneamente.",
    "how.step2": "Resumen IA",
    "how.step2.desc":
      "Nuestra IA analiza tu contrato y crea un resumen claro y conciso de los términos y condiciones clave.",
    "how.step3": "Desbloquear Análisis Completo",
    "how.step3.desc":
      "Obtén explicaciones detalladas de cláusulas complejas, señales de alerta potenciales y fechas importantes.",

    // Community
    "community.title": "Comunidad de Apoyo para Inquilinos",
    "community.subtitle":
      "Obtén ayuda de otros inquilinos y expertos en vivienda. Haz preguntas de forma anónima y comparte tus experiencias.",
    "community.ask": "Hacer una Pregunta",
    "community.browse": "Explorar Preguntas",
    "community.experts": "Respuestas de Expertos",
    "community.category.all": "Todas las Categorías",
    "community.category.rentIncreases": "Incrementos de Renta",
    "community.category.securityDeposits": "Depósitos de Seguridad",
    "community.category.repairsMaintenance": "Reparaciones y Mantenimiento",
    "community.category.neighborIssues": "Problemas de Vecino",
    "community.category.leaseTerms": "Términos de Arrendamiento",
    "community.category.eviction": "Desalojo",
    "community.category.discrimination": "Discriminación",
    "community.category.utilities": "Servicios",
    "community.category.movingOut": "Salida",
    "community.category.other": "Otro",
    "community.location.all": "Todas las Ubicaciones",
    "community.location.california": "California",
    "community.location.texas": "Texas",
    "community.location.newYork": "Nueva York",
    "community.location.florida": "Florida",
    "community.location.illinois": "Illinois",

    // Common
    "common.loading": "Cargando...",
    "common.error": "Error",
    "common.success": "Éxito",
    "common.cancel": "Cancelar",
    "common.save": "Guardar",
    "common.delete": "Eliminar",
    "common.edit": "Editar",

    // Upload
    "upload.formatError": "Por favor, sube un archivo PDF o imagen (JPG, PNG, PDF)",
    "upload.fileSizeError": "El archivo debe ser menor de 10MB. Intenta comprimirlo o tomar una foto más clara.",
    "upload.uploadError": "Ocurrió un error al procesar tu contrato. Por favor, inténtalo de nuevo.",
    "upload.backToHome": "Volver a la página principal",
    "upload.leaseEasy": "Conmates",
    "upload.uploadYourLease": "Subir Su Arrendamiento",
    "upload.uploadInstructions": "Suba su documento de arrendamiento y lo descompondremos en términos simples y fáciles de entender.",
    "upload.analysisComplete": "Análisis Completo!",
    "upload.analysisSuccess": "Hemos analizado exitosamente su arrendamiento. Aquí está lo que encontramos:",
    "upload.viewLeaseSummary": "Ver Resumen de Su Arrendamiento",

    // Support
    "support.describeSituation": "Describe tu situación de vivienda o pregunta...",
    "support.backToHome": "Volver a la página principal",
    "support.humanSupport": "Soporte Humano",
    "support.getHumanSupport": "Obtener Soporte Humano",
    "support.connectWithExperts": "Conecte con expertos en vivienda, asesores y defensores de derechos que entienden su situación y pueden proporcionar ayuda personalizada.",
    "support.facingEmergency": "¿Se enfrenta a una Emergencia?",

    // Resources
    "resources.searchPlaceholder": "Buscar recursos, organizaciones o temas...",
    "resources.tenantRightsCA": "Guía completa de derechos de inquilinos en California, incluyendo control de alquileres, protección contra desalojos y estándares de habitabilidad.",
    "resources.rentStabilizationNY": "Comprender las leyes de estabilización y control de alquileres en la ciudad y el estado de Nueva York.",
    "resources.tenantRightsTX": "Secciones clave del Código de Propiedad de Texas que protegen los derechos de los inquilinos y describen las obligaciones del propietario.",
    "resources.repairRequestTemplate": "Plantilla de carta formal para solicitar reparaciones a tu arrendador con el lenguaje legal adecuado.",
    "resources.securityDepositTemplate": "Plantilla para exigir la devolución del depósito de seguridad con citas legales y plazos.",
    "resources.allStates": "Todos los Estados",
    "resources.california": "California",
    "resources.newYork": "Nueva York",
    "resources.texas": "Texas",
    "resources.florida": "Florida",
    "resources.illinois": "Illinois",

    // Breakdown Page
    "breakdown.analysisTailored": "Análisis adaptado para:",
    "breakdown.stateSpecificRules": "Reglas de Arrendamiento Estatal y Consejos",
    "breakdown.securityDepositLimit": "Límite del Depósito de Seguridad",
    "breakdown.lateFeeLimit": "Límite de Multa",
    "breakdown.noticePeriod": "Período de Notificación",
    "breakdown.requiredDisclosures": "Revelaciones Requeridas",
    "breakdown.tip": "Consejo",
    "breakdown.backToSummary": "Volver al Resumen",
    "breakdown.leaseEasy": "Conmates",
    "breakdown.conmates": "Conmates",
    "breakdown.completeLeaseBreakdown": "Desglose Completo del Arrendamiento",
    "breakdown.leaseExplained": "Tu arrendamiento, explicado en inglés simple.",
    "breakdown.clauseByClause": "Cláusula por Cláusula",
    "breakdown.redFlags": "Señales Rojas",
    "breakdown.actionableTips": "Consejos Aplicables",
    "breakdown.understandingYourLease": "Entendiendo Tu Arrendamiento",
    "breakdown.originalLeaseText": "Texto Original del Arrendamiento",
    "breakdown.whatThisMeans": "Qué Esto Significa",
    "breakdown.proTips": "💡 Consejos Pro",
    "breakdown.potentialRedFlags": "Señales Rojas Potenciales",
    "breakdown.impactOnYou": "Impacto en Ti",
    "breakdown.whatYouCanDo": "Qué Puedes Hacer",
    "breakdown.yourActionPlan": "Tu Plan de Acción",
    "breakdown.shareYourFeedback": "Compartir Tu Retroalimentación",
    "breakdown.howHelpful": "¿Qué tan útil fue este análisis?",
    "breakdown.commentsOptional": "Comentarios (opcionales)",
    "breakdown.whatDidYouFindMostHelpful": "¿Qué te pareció más útil? ¿Qué podríamos mejorar?",
    "breakdown.emailOptional": "Correo Electrónico (opcional)",
    "breakdown.yourEmail": "tu@correo.com",
    "breakdown.emailPrivacy": "Solo lo usaremos para seguir su retroalimentación si es necesario.",
    "breakdown.sending": "Enviando...",
    "breakdown.sendFeedback": "Enviar Retroalimentación",

    // Support Page (Support Options)
    "support.liveChatSupport": "Soporte de Chat en Vivo",
    "support.getInstantHelp": "Obtener ayuda instantánea de nuestros asesores de vivienda",
    "support.phoneConsultation": "Consulta por Teléfono",
    "support.speakWithExpert": "Hablar directamente con un experto en vivienda",
    "support.videoConsultation": "Consulta por Video",
    "support.faceToFaceHelp": "Ayuda cara a cara con revisión de documento",
    "support.emergencyHotline": "Línea de Emergencia",
    "support.urgentHousingIssues": "Problemas de Vivienda Urgentes y Notificaciones de Desalojo",

    // Breakdown Clauses
    "breakdown.clause.rent.title": "Monthly Rent & Payment Terms",
    "breakdown.clause.rent.section": "Section 3: Rent",
    "breakdown.clause.rent.originalText": "Tenant agrees to pay rent in the amount of $2,400.00 per month, due on the first day of each month. Late fees of $75.00 will be assessed for payments received after the 5th day of the month.",
    "breakdown.clause.rent.explanation": "You'll pay $2,400 every month, and it's due on the 1st. If you're late (after the 5th), you'll be charged a $75 late fee. This is pretty standard, but the late fee is on the higher side.",
    "breakdown.clause.rent.tip1": "Set up automatic payments to avoid the $75 late fee",
    "breakdown.clause.rent.tip2": "The 5-day grace period is reasonable - use it if needed",
    "breakdown.clause.rent.tip3": "Consider negotiating a lower late fee if you have good credit",
    "breakdown.clause.deposit.title": "Security Deposit",
    "breakdown.clause.deposit.section": "Section 4: Security Deposit",
    "breakdown.clause.deposit.originalText": "Tenant shall deposit with Landlord the sum of $2,400.00 as security for the faithful performance of Tenant's obligations. This deposit may be used to cover unpaid rent, damages beyond normal wear and tear, or cleaning costs.",
    "breakdown.clause.deposit.explanation": "You're putting down $2,400 as a security deposit (same as one month's rent). This money protects the landlord if you damage the place, don't pay rent, or leave it messy. You should get most or all of it back if you take good care of the apartment.",
    "breakdown.clause.deposit.tip1": "Document the apartment's condition when you move in with photos",
    "breakdown.clause.deposit.tip2": "Keep receipts for any improvements or repairs you make",
    "breakdown.clause.deposit.tip3": "Give proper notice when moving out to ensure deposit return",
    "breakdown.clause.term.title": "Lease Duration & Renewal",
    "breakdown.clause.term.section": "Section 2: Term",
    "breakdown.clause.term.originalText": "This lease shall commence on January 1, 2024, and terminate on December 31, 2024. Tenant may renew for additional one-year terms with 60 days written notice and Landlord's consent.",
    "breakdown.clause.term.explanation": "Your lease runs for exactly one year, from January 1st to December 31st, 2024. If you want to stay longer, you need to tell your landlord in writing at least 60 days before the lease ends, but they don't have to say yes.",
    "breakdown.clause.term.tip1": "Mark your calendar for November 1st to start renewal discussions",
    "breakdown.clause.term.tip2": "Start looking for alternatives early if renewal isn't guaranteed",
    "breakdown.clause.term.tip3": "Ask about renewal terms and potential rent increases upfront",
    "breakdown.clause.maintenance.title": "Maintenance & Repairs",
    "breakdown.clause.maintenance.section": "Section 8: Maintenance",
    "breakdown.clause.maintenance.originalText": "Landlord shall maintain the premises in habitable condition. Tenant is responsible for minor repairs under $100 and must report major issues within 48 hours of discovery.",
    "breakdown.clause.maintenance.explanation": "Your landlord has to keep the place livable (working heat, plumbing, etc.), but you're responsible for small fixes under $100. If something major breaks, you need to tell them within 2 days or you might be held responsible.",
    "breakdown.clause.maintenance.tip1": "Report issues immediately via email to create a paper trail",
    "breakdown.clause.maintenance.tip2": "Keep receipts for any repairs you make under $100",
    "breakdown.clause.maintenance.tip3": "Know what counts as 'habitable' - heat, water, electricity, safe structure",
    "breakdown.clause.pets.title": "Pet Policy",
    "breakdown.clause.pets.section": "Section 12: Pets",
    "breakdown.clause.pets.originalText": "No pets, animals, or livestock of any kind are permitted on the premises without prior written consent of Landlord, which may be withheld at Landlord's sole discretion.",
    "breakdown.clause.pets.explanation": "No pets allowed, period. Even if you ask nicely, your landlord can say no for any reason. This includes everything from dogs and cats to fish and hamsters.",
    "breakdown.clause.pets.tip1": "If you need a service animal, know your rights under the ADA",
    "breakdown.clause.pets.tip2": "Consider this carefully if you might want a pet during your lease",
    "breakdown.clause.pets.tip3": "Ask about pet policies before signing if this matters to you",
    "breakdown.clause.subletting.title": "Subletting & Assignment",
    "breakdown.clause.subletting.section": "Section 15: Assignment",
    "breakdown.clause.subletting.originalText": "Tenant may not assign this lease or sublet the premises, in whole or in part, without the prior written consent of Landlord. Any unauthorized assignment or subletting shall be grounds for immediate termination.",
    "breakdown.clause.subletting.explanation": "You can't let someone else live there or take over your lease without your landlord's written permission. If you do it anyway, they can kick you out immediately. This limits your flexibility if your situation changes.",
    "breakdown.clause.subletting.tip1": "Discuss subletting policies upfront if you might need flexibility",
    "breakdown.clause.subletting.tip2": "Get any subletting agreements in writing",
    "breakdown.clause.subletting.tip3": "Consider negotiating more flexible terms if you travel frequently",
    // Breakdown Red Flags
    "breakdown.redflag.noPetPolicy.title": "Strict No-Pet Policy",
    "breakdown.redflag.noPetPolicy.description": "The lease completely prohibits pets without any exceptions, which could be problematic if your circumstances change.",
    "breakdown.redflag.noPetPolicy.impact": "This inflexibility could force you to choose between your living situation and a pet, even for emotional support animals.",
    "breakdown.redflag.noPetPolicy.action": "Consider negotiating pet terms upfront or look for pet-friendly alternatives if this matters to you.",
    "breakdown.redflag.noSubletting.title": "No Subletting Rights",
    "breakdown.redflag.noSubletting.description": "You cannot sublet or assign your lease under any circumstances without landlord approval, which they can deny for any reason.",
    "breakdown.redflag.noSubletting.impact": "If you need to move early for work, family, or financial reasons, you'll be stuck paying rent for an empty apartment.",
    "breakdown.redflag.noSubletting.action": "Negotiate subletting rights or early termination clauses before signing.",
    "breakdown.redflag.highLateFee.title": "High Late Fee",
    "breakdown.redflag.highLateFee.description": "The $75 late fee is above average for this rent amount (typically 3-5% of monthly rent).",
    "breakdown.redflag.highLateFee.impact": "One late payment could cost you $75, which adds up quickly if you're occasionally late.",
    "breakdown.redflag.highLateFee.action": "Set up automatic payments and negotiate a lower late fee if possible.",
    "breakdown.redflag.tenantRepairs.title": "Tenant Responsible for Minor Repairs",
    "breakdown.redflag.tenantRepairs.description": "You're responsible for all repairs under $100, which could add up over time.",
    "breakdown.redflag.tenantRepairs.impact": "Small repairs like clogged drains, light fixtures, or cabinet handles become your expense.",
    "breakdown.redflag.tenantRepairs.action": "Budget for minor repairs and document all maintenance issues when you move in.",
    // Breakdown Actionable Tips
    "breakdown.tips.beforeSign.category": "Before You Sign",
    "breakdown.tips.beforeSign.tip1": "Take detailed photos/videos of the apartment's condition",
    "breakdown.tips.beforeSign.tip2": "Test all appliances, faucets, lights, and outlets",
    "breakdown.tips.beforeSign.tip3": "Ask about the landlord's typical response time for repairs",
    "breakdown.tips.beforeSign.tip4": "Clarify what 'normal wear and tear' means to avoid deposit disputes",
    "breakdown.tips.beforeSign.tip5": "Get all verbal promises in writing as lease addendums",
    "breakdown.tips.financialProtection.category": "Financial Protection",
    "breakdown.tips.financialProtection.tip1": "Set up automatic rent payments to avoid the $75 late fee",
    "breakdown.tips.financialProtection.tip2": "Budget an extra $50-100/month for minor repairs you'll be responsible for",
    "breakdown.tips.financialProtection.tip3": "Keep your security deposit in a separate savings account mentally",
    "breakdown.tips.financialProtection.tip4": "Document any improvements you make with receipts",
    "breakdown.tips.financialProtection.tip5": "Consider renter's insurance to protect your belongings",
    "breakdown.tips.duringLease.category": "During Your Lease",
    "breakdown.tips.duringLease.tip1": "Report maintenance issues immediately via email for paper trail",
    "breakdown.tips.duringLease.tip2": "Pay rent on time every month - late fees add up quickly",
    "breakdown.tips.duringLease.tip3": "Keep copies of all communications with your landlord",
    "breakdown.tips.duringLease.tip4": "Take photos before and after any repairs you make",
    "breakdown.tips.duringLease.tip5": "Be a good neighbor to maintain positive landlord relationship",
    "breakdown.tips.planningExit.category": "Planning Your Exit",
    "breakdown.tips.planningExit.tip1": "Mark November 1st on your calendar to discuss renewal",
    "breakdown.tips.planningExit.tip2": "Start planning 90 days before lease end if you're not renewing",
    "breakdown.tips.planningExit.tip3": "Clean thoroughly and repair any damage before move-out inspection",
    "breakdown.tips.planningExit.tip4": "Provide proper written notice as required by your lease",
    "breakdown.tips.planningExit.tip5": "Do a final walkthrough with your landlord and get it documented",
    // Homepage (expanded i18n)
    "home.leaseEasy": "Conmates",
    "home.meetAIAssistant": "Conocé a tu Asistente Virtual",
    "home.poweredByGPT4": "Potenciado por GPT-4",
    "home.aiAssistantDescription": "Obtén ayuda instantánea, inteligente las 24 horas del día, los 7 días de la semana. Nuestro asistente virtual entiende acuerdos de arrendamiento, derechos de inquilino y puede guiarte a través de cualquier situación de alquiler.",
    "home.leaseAnalysis": "Análisis de Arrendamiento",
    "home.leaseAnalysisDesc": "Sube tu arrendamiento y obtén explicaciones instantáneas de términos y cláusulas complejas.",
    "home.realTimeChat": "Chat en Tiempo Real",
    "home.realTimeChatDesc": "Pregunta preguntas y obtén respuestas inmediatas, contextuales sobre tu situación de alquiler.",
    "home.legalGuidance": "Asesoría Legal",
    "home.legalGuidanceDesc": "Aprende sobre derechos de inquilino y obtén orientación sobre cómo manejar disputas de alquiler.",
    "home.startChattingNow": "Comienza a Chatear Ahora",
    "home.completeSupportEcosystem": "Ecosistema Completo de Soporte para Inquilinos",
    "home.communitySupport": "Soporte de Comunidad",
    "home.communitySupportDesc": "Obtén ayuda de otros inquilinos y expertos en vivienda en nuestro foro Q&A anónimo.",
    "home.legalResources": "Recursos Legales",
    "home.legalResourcesDesc": "Accede a guías de derechos de inquilino estatales y organizaciones de ayuda legal.",
    "home.smartAlerts": "Alertas Inteligentes",
    "home.smartAlertsDesc": "Nunca te pierdas fechas límites de alquiler con notificaciones proactivas.",
    "home.humanSupport": "Soporte Humano",
    "home.humanSupportDesc": "Conecta con asesores de vivienda y obtén ayuda personalizada.",
    "home.readyToUnderstand": "¿Listo para entender tu arrendamiento?",
    "home.readyToUnderstandDesc": "Únete a miles de inquilinos que han simplificado su comprensión del arrendamiento con Conmates.",
    "home.getStartedNow": "Comienza Ahora",
    "home.tryAIAssistant": "Prueba AI Assistant",
    "home.footerDesc": "Haciendo que los acuerdos de arrendamiento sean simples y comprensibles para todos. Potenciado por IA, diseñado para la claridad.",
    "home.platform": "Plataforma",
    "home.legal": "Legal",
    "home.privacyPolicy": "Política de Privacidad",
    "home.termsOfService": "Términos de Servicio",
    "home.about": "Acerca de",
    "home.contact": "Contacto",
    "home.copyright": "© 2024 Conmates. Todos los derechos reservados.",
    // Payment page translations
    "payment.completeYourPurchase": "Complete Su Compra",
    "payment.securePayment": "Pago Seguro",
    "payment.leaseAnalysis": "Análisis de Arrendamiento",
    "payment.instantAccess": "Acceso Instantáneo",
    "payment.oneTimePayment": "Pago único",
    "payment.whatsIncluded": "Qué está Incluido",
    "payment.aiAnalysis": "Análisis de arrendamiento con IA",
    "payment.clauseBreakdown": "Desglose cláusula por cláusula",
    "payment.redFlagDetection": "Detección de señales de alerta",
    "payment.pdfReport": "Descarga de informe PDF",
    "payment.communityAccess": "Acceso a la comunidad",
    "payment.emailAddress": "Dirección de Correo Electrónico",
    "payment.enterEmail": "Ingrese su correo electrónico",
    "payment.fullName": "Nombre Completo",
    "payment.enterName": "Ingrese su nombre completo",
    "payment.processing": "Procesando...",
    "payment.payNow": "Pagar Ahora",
    "payment.stripeSecurity": "Su pago es seguro y nunca almacenamos sus datos financieros. Todas las transacciones se procesan a través de los servidores seguros de Stripe.",
    "payment.moneyBackGuarantee": "Garantía de Devolución de Dinero de 30 Días",
    "payment.guaranteeDescription": "¿No está satisfecho? Obtenga un reembolso completo dentro de 30 días, sin preguntas.",

    // Payment success page translations
    "payment.success.title": "¡Pago Exitoso!",
    "payment.success.description": "Gracias por su compra. Ahora tiene acceso a todas las funciones de Conmates.",
    "payment.success.orderDetails": "Detalles del Pedido",
    "payment.success.product": "Producto",
    "payment.success.amount": "Cantidad",
    "payment.success.status": "Estado",
    "payment.success.paid": "Pagado",
    "payment.success.transactionId": "ID de Transacción",
    "payment.success.nextSteps": "Próximos Pasos",
    "payment.success.step1.title": "Subir Su Arrendamiento",
    "payment.success.step1.description": "Vaya a la página de carga y envíe su documento de arrendamiento para análisis.",
    "payment.success.step2.title": "Obtener Su Análisis",
    "payment.success.step2.description": "Reciba un desglose completo de los términos y condiciones de su arrendamiento.",
    "payment.success.step3.title": "Descargar Informe",
    "payment.success.step3.description": "Descargue su informe PDF detallado para referencia futura.",
    "payment.success.uploadLease": "Subir Arrendamiento",
    "payment.success.goToDashboard": "Ir al Panel de Control",
    "payment.success.securityTitle": "Transacción Segura",
    "payment.success.securityDescription": "Su pago ha sido procesado de forma segura a través de Stripe. Recibirá un correo de confirmación pronto.",
    "payment.success.needHelp": "¿Necesita ayuda para comenzar?",
    "payment.success.contactSupport": "Contactar Soporte",
  },
  zh: {
    // Navigation
    "nav.home": "首页",
    "nav.upload": "上传租约",
    "nav.community": "社区",
    "nav.resources": "资源",
    "nav.alerts": "提醒",
    "nav.support": "支持",

    // Homepage
    "home.aiAssistant": "AI Assistant",
    "home.community": "社区",
    "home.resources": "资源",
    "home.payment": "支付",
    "home.alerts": "提醒",
    "home.support": "支持",
    "home.youSelected": "你选择了",
    "home.hero.title": "用简单中文理解您的租约",
    "home.hero.subtitle": "上传您的租约文件，获得AI驱动的摘要，将复杂的法律术语分解为简单易懂的语言。",
    "home.hero.cta": "上传租约",
    "home.askAIAssistant": "询问AI助手",
    "how.title": "工作原理",
    "how.step1": "上传",
    "how.step1.desc": "只需以PDF格式上传您的租约文件。我们的安全系统会立即处理。",
    "how.step2": "AI摘要",
    "how.step2.desc": "我们的AI分析您的租约并创建关键条款和条件的清晰简洁摘要。",
    "how.step3": "解锁完整分析",
    "how.step3.desc": "获得复杂条款的详细解释、潜在危险信号和重要日期。",

    // Community
    "community.title": "租户支持社区",
    "community.subtitle": "从其他租户和住房专家那里获得帮助。匿名提问并分享您的经验。",
    "community.ask": "提问",
    "community.browse": "浏览问题",
    "community.experts": "专家回答",
    "community.category.all": "所有类别",
    "community.category.rentIncreases": "租金增加",
    "community.category.securityDeposits": "安全押金",
    "community.category.repairsMaintenance": "维修和保养",
    "community.category.neighborIssues": "邻居问题",
    "community.category.leaseTerms": "租赁条款",
    "community.category.eviction": "驱逐",
    "community.category.discrimination": "歧视",
    "community.category.utilities": "服务",
    "community.category.movingOut": "搬出",
    "community.category.other": "其他",
    "community.location.all": "所有位置",
    "community.location.california": "加利福尼亚",

    // Common
    "common.loading": "加载中...",
    "common.error": "错误",
    "common.success": "成功",
    "common.cancel": "取消",
    "common.save": "保存",
    "common.delete": "删除",
    "common.edit": "编辑",

    // Upload
    "upload.formatError": "请上传PDF或图片文件（JPG、PNG、PDF）",
    "upload.fileSizeError": "文件大小必须小于10MB。请尝试压缩文件或拍摄更清晰的照片。",
    "upload.uploadError": "处理您的租约时出错。请再试一次。",

    // Support
    "support.describeSituation": "描述您的住房情况或问题...",

    // Resources
    "resources.searchPlaceholder": "搜索资源、组织或主题...",
    "resources.tenantRightsCA": "加利福尼亚州租户权利的综合指南，包括租金管制、驱逐保护和适居标准。",
    "resources.rentStabilizationNY": "了解纽约市和纽约州的租金稳定和租金管制法律。",
    "resources.tenantRightsTX": "德克萨斯州物业法保护租户权利并规定房东义务的关键条款。",
    "resources.repairRequestTemplate": "正式的维修请求信模板，使用适当的法律用语向房东提出维修请求。",
    "resources.securityDepositTemplate": "要求退还押金的模板，包含法律引用和截止日期。",
    "resources.allStates": "所有州",
    "resources.california": "加利福尼亚",
    "resources.newYork": "纽约",
    "resources.texas": "德克萨斯",
    "resources.florida": "佛罗里达",
    "resources.illinois": "伊利诺伊",

    // Breakdown Page
    "breakdown.analysisTailored": "分析量身定制：",
    "breakdown.stateSpecificRules": "州特定租赁规则和提示",
    "breakdown.securityDepositLimit": "安全押金限额",
    "breakdown.lateFeeLimit": "滞纳金限额",
    "breakdown.noticePeriod": "通知期",
    "breakdown.requiredDisclosures": "所需披露",
    "breakdown.tip": "提示",
    "breakdown.backToSummary": "返回摘要",
    "breakdown.leaseEasy": "Conmates",
    "breakdown.conmates": "Conmates",
    "breakdown.completeLeaseBreakdown": "完整租赁分解",
    "breakdown.leaseExplained": "您的租赁，用简单英语解释。",
    "breakdown.clauseByClause": "条款对条款",
    "breakdown.redFlags": "红色标志",
    "breakdown.actionableTips": "可操作提示",
    "breakdown.understandingYourLease": "了解您的租赁",
    "breakdown.originalLeaseText": "原始租赁文本",
    "breakdown.whatThisMeans": "这意味着什么",
    "breakdown.proTips": "💡 专业提示",
    "breakdown.potentialRedFlags": "潜在红色标志",
    "breakdown.impactOnYou": "对你产生的影响",
    "breakdown.whatYouCanDo": "你可以做什么",
    "breakdown.yourActionPlan": "你的行动计划",
    "breakdown.shareYourFeedback": "分享您的反馈",
    "breakdown.howHelpful": "这个分析有多有用？",
    "breakdown.commentsOptional": "评论（可选）",
    "breakdown.whatDidYouFindMostHelpful": "你发现什么最有帮助？我们可以改进什么？",
    "breakdown.emailOptional": "电子邮件（可选）",
    "breakdown.yourEmail": "your@email.com",
    "breakdown.emailPrivacy": "我们只会使用它来跟进你的反馈（如果需要）。",
    "breakdown.sending": "发送中...",
    "breakdown.sendFeedback": "发送反馈",

    // Support Page (Support Options)
    "support.liveChatSupport": "实时聊天支持",
    "support.getInstantHelp": "从我们的住房顾问那里获得即时帮助",
    "support.phoneConsultation": "电话咨询",
    "support.speakWithExpert": "直接与住房专家交谈",
    "support.videoConsultation": "视频咨询",
    "support.faceToFaceHelp": "面对面帮助文档审查",
    "support.emergencyHotline": "紧急热线",
    "support.urgentHousingIssues": "紧急住房问题和驱逐通知",

    // Breakdown Clauses
    "breakdown.clause.rent.title": "Monthly Rent & Payment Terms",
    "breakdown.clause.rent.section": "Section 3: Rent",
    "breakdown.clause.rent.originalText": "Tenant agrees to pay rent in the amount of $2,400.00 per month, due on the first day of each month. Late fees of $75.00 will be assessed for payments received after the 5th day of the month.",
    "breakdown.clause.rent.explanation": "You'll pay $2,400 every month, and it's due on the 1st. If you're late (after the 5th), you'll be charged a $75 late fee. This is pretty standard, but the late fee is on the higher side.",
    "breakdown.clause.rent.tip1": "Set up automatic payments to avoid the $75 late fee",
    "breakdown.clause.rent.tip2": "The 5-day grace period is reasonable - use it if needed",
    "breakdown.clause.rent.tip3": "Consider negotiating a lower late fee if you have good credit",
    "breakdown.clause.deposit.title": "Security Deposit",
    "breakdown.clause.deposit.section": "Section 4: Security Deposit",
    "breakdown.clause.deposit.originalText": "Tenant shall deposit with Landlord the sum of $2,400.00 as security for the faithful performance of Tenant's obligations. This deposit may be used to cover unpaid rent, damages beyond normal wear and tear, or cleaning costs.",
    "breakdown.clause.deposit.explanation": "You're putting down $2,400 as a security deposit (same as one month's rent). This money protects the landlord if you damage the place, don't pay rent, or leave it messy. You should get most or all of it back if you take good care of the apartment.",
    "breakdown.clause.deposit.tip1": "Document the apartment's condition when you move in with photos",
    "breakdown.clause.deposit.tip2": "Keep receipts for any improvements or repairs you make",
    "breakdown.clause.deposit.tip3": "Give proper notice when moving out to ensure deposit return",
    "breakdown.clause.term.title": "Lease Duration & Renewal",
    "breakdown.clause.term.section": "Section 2: Term",
    "breakdown.clause.term.originalText": "This lease shall commence on January 1, 2024, and terminate on December 31, 2024. Tenant may renew for additional one-year terms with 60 days written notice and Landlord's consent.",
    "breakdown.clause.term.explanation": "Your lease runs for exactly one year, from January 1st to December 31st, 2024. If you want to stay longer, you need to tell your landlord in writing at least 60 days before the lease ends, but they don't have to say yes.",
    "breakdown.clause.term.tip1": "Mark your calendar for November 1st to start renewal discussions",
    "breakdown.clause.term.tip2": "Start looking for alternatives early if renewal isn't guaranteed",
    "breakdown.clause.term.tip3": "Ask about renewal terms and potential rent increases upfront",
    "breakdown.clause.maintenance.title": "Maintenance & Repairs",
    "breakdown.clause.maintenance.section": "Section 8: Maintenance",
    "breakdown.clause.maintenance.originalText": "Landlord shall maintain the premises in habitable condition. Tenant is responsible for minor repairs under $100 and must report major issues within 48 hours of discovery.",
    "breakdown.clause.maintenance.explanation": "Your landlord has to keep the place livable (working heat, plumbing, etc.), but you're responsible for small fixes under $100. If something major breaks, you need to tell them within 2 days or you might be held responsible.",
    "breakdown.clause.maintenance.tip1": "Report issues immediately via email to create a paper trail",
    "breakdown.clause.maintenance.tip2": "Keep receipts for any repairs you make under $100",
    "breakdown.clause.maintenance.tip3": "Know what counts as 'habitable' - heat, water, electricity, safe structure",
    "breakdown.clause.pets.title": "Pet Policy",
    "breakdown.clause.pets.section": "Section 12: Pets",
    "breakdown.clause.pets.originalText": "No pets, animals, or livestock of any kind are permitted on the premises without prior written consent of Landlord, which may be withheld at Landlord's sole discretion.",
    "breakdown.clause.pets.explanation": "No pets allowed, period. Even if you ask nicely, your landlord can say no for any reason. This includes everything from dogs and cats to fish and hamsters.",
    "breakdown.clause.pets.tip1": "If you need a service animal, know your rights under the ADA",
    "breakdown.clause.pets.tip2": "Consider this carefully if you might want a pet during your lease",
    "breakdown.clause.pets.tip3": "Ask about pet policies before signing if this matters to you",
    "breakdown.clause.subletting.title": "Subletting & Assignment",
    "breakdown.clause.subletting.section": "Section 15: Assignment",
    "breakdown.clause.subletting.originalText": "Tenant may not assign this lease or sublet the premises, in whole or in part, without the prior written consent of Landlord. Any unauthorized assignment or subletting shall be grounds for immediate termination.",
    "breakdown.clause.subletting.explanation": "You can't let someone else live there or take over your lease without your landlord's written permission. If you do it anyway, they can kick you out immediately. This limits your flexibility if your situation changes.",
    "breakdown.clause.subletting.tip1": "Discuss subletting policies upfront if you might need flexibility",
    "breakdown.clause.subletting.tip2": "Get any subletting agreements in writing",
    "breakdown.clause.subletting.tip3": "Consider negotiating more flexible terms if you travel frequently",
    // Breakdown Red Flags
    "breakdown.redflag.noPetPolicy.title": "Strict No-Pet Policy",
    "breakdown.redflag.noPetPolicy.description": "The lease completely prohibits pets without any exceptions, which could be problematic if your circumstances change.",
    "breakdown.redflag.noPetPolicy.impact": "This inflexibility could force you to choose between your living situation and a pet, even for emotional support animals.",
    "breakdown.redflag.noPetPolicy.action": "Consider negotiating pet terms upfront or look for pet-friendly alternatives if this matters to you.",
    "breakdown.redflag.noSubletting.title": "No Subletting Rights",
    "breakdown.redflag.noSubletting.description": "You cannot sublet or assign your lease under any circumstances without landlord approval, which they can deny for any reason.",
    "breakdown.redflag.noSubletting.impact": "If you need to move early for work, family, or financial reasons, you'll be stuck paying rent for an empty apartment.",
    "breakdown.redflag.noSubletting.action": "Negotiate subletting rights or early termination clauses before signing.",
    "breakdown.redflag.highLateFee.title": "High Late Fee",
    "breakdown.redflag.highLateFee.description": "The $75 late fee is above average for this rent amount (typically 3-5% of monthly rent).",
    "breakdown.redflag.highLateFee.impact": "One late payment could cost you $75, which adds up quickly if you're occasionally late.",
    "breakdown.redflag.highLateFee.action": "Set up automatic payments and negotiate a lower late fee if possible.",
    "breakdown.redflag.tenantRepairs.title": "Tenant Responsible for Minor Repairs",
    "breakdown.redflag.tenantRepairs.description": "You're responsible for all repairs under $100, which could add up over time.",
    "breakdown.redflag.tenantRepairs.impact": "Small repairs like clogged drains, light fixtures, or cabinet handles become your expense.",
    "breakdown.redflag.tenantRepairs.action": "Budget for minor repairs and document all maintenance issues when you move in.",
    // Breakdown Actionable Tips
    "breakdown.tips.beforeSign.category": "Before You Sign",
    "breakdown.tips.beforeSign.tip1": "Take detailed photos/videos of the apartment's condition",
    "breakdown.tips.beforeSign.tip2": "Test all appliances, faucets, lights, and outlets",
    "breakdown.tips.beforeSign.tip3": "Ask about the landlord's typical response time for repairs",
    "breakdown.tips.beforeSign.tip4": "Clarify what 'normal wear and tear' means to avoid deposit disputes",
    "breakdown.tips.beforeSign.tip5": "Get all verbal promises in writing as lease addendums",
    "breakdown.tips.financialProtection.category": "Financial Protection",
    "breakdown.tips.financialProtection.tip1": "Set up automatic rent payments to avoid the $75 late fee",
    "breakdown.tips.financialProtection.tip2": "Budget an extra $50-100/month for minor repairs you'll be responsible for",
    "breakdown.tips.financialProtection.tip3": "Keep your security deposit in a separate savings account mentally",
    "breakdown.tips.financialProtection.tip4": "Document any improvements you make with receipts",
    "breakdown.tips.financialProtection.tip5": "Consider renter's insurance to protect your belongings",
    "breakdown.tips.duringLease.category": "During Your Lease",
    "breakdown.tips.duringLease.tip1": "Report maintenance issues immediately via email for paper trail",
    "breakdown.tips.duringLease.tip2": "Pay rent on time every month - late fees add up quickly",
    "breakdown.tips.duringLease.tip3": "Keep copies of all communications with your landlord",
    "breakdown.tips.duringLease.tip4": "Take photos before and after any repairs you make",
    "breakdown.tips.duringLease.tip5": "Be a good neighbor to maintain positive landlord relationship",
    "breakdown.tips.planningExit.category": "Planning Your Exit",
    "breakdown.tips.planningExit.tip1": "Mark November 1st on your calendar to discuss renewal",
    "breakdown.tips.planningExit.tip2": "Start planning 90 days before lease end if you're not renewing",
    "breakdown.tips.planningExit.tip3": "Clean thoroughly and repair any damage before move-out inspection",
    "breakdown.tips.planningExit.tip4": "Provide proper written notice as required by your lease",
    "breakdown.tips.planningExit.tip5": "Do a final walkthrough with your landlord and get it documented",
    // Homepage (expanded i18n)
    "home.leaseEasy": "Conmates",
    "home.meetAIAssistant": "认识您的AI助手",
    "home.poweredByGPT4": "由GPT-4驱动",
    "home.aiAssistantDescription": "全天候24/7获得智能帮助。我们的AI助手理解租赁协议、租户权利，并能指导您应对任何租赁情况。",
    "home.leaseAnalysis": "租赁分析",
    "home.leaseAnalysisDesc": "上传您的租赁合同，立即获得复杂条款的解释。",
    "home.realTimeChat": "实时聊天",
    "home.realTimeChatDesc": "提问并获得关于您的租赁情况的即时、上下文响应。",
    "home.legalGuidance": "法律指导",
    "home.legalGuidanceDesc": "了解租户权利并获得处理租赁纠纷的指导。",
    "home.startChattingNow": "立即开始聊天",
    "home.completeSupportEcosystem": "完整租户支持生态系统",
    "home.communitySupport": "社区支持",
    "home.communitySupportDesc": "在我们的匿名问答论坛中获得其他租户和住房专家的帮助。",
    "home.legalResources": "法律资源",
    "home.legalResourcesDesc": "访问特定州的租户权利指南和法律援助组织。",
    "home.smartAlerts": "智能提醒",
    "home.smartAlertsDesc": "通过主动通知，永不错过重要的租赁截止日期。",
    "home.humanSupport": "人工支持",
    "home.humanSupportDesc": "与住房顾问联系，获得个性化帮助。",
    "home.readyToUnderstand": "准备好了解您的租赁了吗？",
    "home.readyToUnderstandDesc": "加入成千上万的租户，简化他们对租赁的理解，使用Conmates。",
    "home.getStartedNow": "立即开始",
    "home.tryAIAssistant": "试用AI助手",
    "home.footerDesc": "让租赁协议变得简单易懂。由AI驱动，专为清晰设计。",
    "home.platform": "平台",
    "home.legal": "法律",
    "home.privacyPolicy": "隐私政策",
    "home.termsOfService": "服务条款",
    "home.about": "关于",
    "home.contact": "联系",
    "home.copyright": "© 2024 租赁易。保留所有权利。",
    // Payment page translations
    "payment.completeYourPurchase": "完成您的购买",
    "payment.securePayment": "安全支付",
    "payment.leaseAnalysis": "租赁分析",
    "payment.instantAccess": "即时访问",
    "payment.oneTimePayment": "一次性付款",
    "payment.whatsIncluded": "包含内容",
    "payment.aiAnalysis": "AI驱动的租赁分析",
    "payment.clauseBreakdown": "逐条分析",
    "payment.redFlagDetection": "危险信号检测",
    "payment.pdfReport": "PDF报告下载",
    "payment.communityAccess": "社区访问",
    "payment.emailAddress": "电子邮件地址",
    "payment.enterEmail": "输入您的电子邮件",
    "payment.fullName": "全名",
    "payment.enterName": "输入您的全名",
    "payment.processing": "处理中...",
    "payment.payNow": "立即支付",
    "payment.stripeSecurity": "您的支付是安全的，我们从不存储您的财务数据。所有交易都通过Stripe的安全服务器处理。",
    "payment.moneyBackGuarantee": "30天退款保证",
    "payment.guaranteeDescription": "不满意？30天内获得全额退款，无需任何问题。",

    // Payment success page translations
    "payment.success.title": "支付成功！",
    "payment.success.description": "感谢您的购买。您现在可以访问Conmates的所有功能。",
    "payment.success.orderDetails": "订单详情",
    "payment.success.product": "产品",
    "payment.success.amount": "金额",
    "payment.success.status": "状态",
    "payment.success.paid": "已支付",
    "payment.success.transactionId": "交易ID",
    "payment.success.nextSteps": "下一步",
    "payment.success.step1.title": "上传您的租赁",
    "payment.success.step1.description": "转到上传页面并提交您的租赁文件进行分析。",
    "payment.success.step2.title": "获取您的分析",
    "payment.success.step2.description": "获得租赁条款和条件的全面分析。",
    "payment.success.step3.title": "下载报告",
    "payment.success.step3.description": "下载详细的PDF报告以供将来参考。",
    "payment.success.uploadLease": "上传租赁",
    "payment.success.goToDashboard": "转到仪表板",
    "payment.success.securityTitle": "安全交易",
    "payment.success.securityDescription": "您的付款已通过Stripe安全处理。您将很快收到确认电子邮件。",
    "payment.success.needHelp": "需要帮助开始？",
    "payment.success.contactSupport": "联系支持",
  },
  hi: {
    // Hindi translations (placeholders for now)
    "nav.home": "होम",
    "nav.upload": "लीज़ अपलोड करें",
    "nav.community": "समुदाय",
    "nav.resources": "संसाधन",
    "nav.payment": "भुगतान",
    "nav.alerts": "अलर्ट",
    "nav.support": "सहायता",
    "home.payment": "भुगतान",
    "hero.title": "सरल हिंदी में अपनी लीज़ समझें",
    "hero.subtitle": "अपना लीज़ दस्तावेज़ अपलोड करें और एआई-संचालित सारांश प्राप्त करें जो जटिल कानूनी शब्दों को सरल, समझने योग्य भाषा में तोड़ता है।",
    "hero.cta": "लीज़ अपलोड करें",
    "how.title": "कैसे काम करता है",
    "how.step1": "अपलोड करें",
    "how.step1.desc": "बस अपना लीज़ दस्तावेज़ PDF प्रारूप में अपलोड करें। हमारी सुरक्षित प्रणाली इसे तुरंत प्रोसेस करती है।",
    "how.step2": "एआई सारांश",
    "how.step2.desc": "हमारा एआई आपके लीज़ का विश्लेषण करता है और मुख्य शर्तों और नियमों का स्पष्ट, संक्षिप्त सारांश बनाता है।",
    "how.step3": "पूर्ण विश्लेषण अनलॉक करें",
    "how.step3.desc": "जटिल धाराओं, संभावित लाल झंडों और महत्वपूर्ण तिथियों की विस्तृत व्याख्याएँ प्राप्त करें।",
    
    // Payment page translations
    "payment.completeYourPurchase": "अपनी खरीद पूरी करें",
    "payment.securePayment": "सुरक्षित भुगतान",
    "payment.leaseAnalysis": "लीज़ विश्लेषण",
    "payment.instantAccess": "तत्काल पहुंच",
    "payment.oneTimePayment": "एक बार का भुगतान",
    "payment.whatsIncluded": "क्या शामिल है",
    "payment.aiAnalysis": "AI-संचालित लीज़ विश्लेषण",
    "payment.clauseBreakdown": "धारा-दर-धारा विश्लेषण",
    "payment.redFlagDetection": "लाल झंडा पहचान",
    "payment.pdfReport": "PDF रिपोर्ट डाउनलोड",
    "payment.communityAccess": "समुदाय पहुंच",
    "payment.emailAddress": "ईमेल पता",
    "payment.enterEmail": "अपना ईमेल दर्ज करें",
    "payment.fullName": "पूरा नाम",
    "payment.enterName": "अपना पूरा नाम दर्ज करें",
    "payment.processing": "प्रोसेसिंग...",
    "payment.payNow": "अभी भुगतान करें",
    "payment.stripeSecurity": "आपका भुगतान सुरक्षित है, और हम कभी भी आपका वित्तीय डेटा संग्रहित नहीं करते। सभी लेन-देन Stripe के सुरक्षित सर्वर के माध्यम से संसाधित किए जाते हैं।",
    "payment.moneyBackGuarantee": "30-दिन की धन वापसी गारंटी",
    "payment.guaranteeDescription": "संतुष्ट नहीं? 30 दिनों के भीतर पूर्ण धनवापसी प्राप्त करें, कोई प्रश्न नहीं।",

    // Payment success page translations
    "payment.success.title": "भुगतान सफल!",
    "payment.success.description": "आपकी खरीद के लिए धन्यवाद। अब आपके पास Conmates की सभी सुविधाओं तक पहुंच है।",
    "payment.success.orderDetails": "ऑर्डर विवरण",
    "payment.success.product": "उत्पाद",
    "payment.success.amount": "राशि",
    "payment.success.status": "स्थिति",
    "payment.success.paid": "भुगतान किया गया",
    "payment.success.transactionId": "लेन-देन ID",
    "payment.success.nextSteps": "अगले कदम",
    "payment.success.step1.title": "अपनी लीज़ अपलोड करें",
    "payment.success.step1.description": "अपलोड पेज पर जाएं और विश्लेषण के लिए अपना लीज़ दस्तावेज़ जमा करें।",
    "payment.success.step2.title": "अपना विश्लेषण प्राप्त करें",
    "payment.success.step2.description": "अपने लीज़ के नियमों और शर्तों का व्यापक विश्लेषण प्राप्त करें।",
    "payment.success.step3.title": "रिपोर्ट डाउनलोड करें",
    "payment.success.step3.description": "भविष्य के संदर्भ के लिए अपनी विस्तृत PDF रिपोर्ट डाउनलोड करें।",
    "payment.success.uploadLease": "लीज़ अपलोड करें",
    "payment.success.goToDashboard": "डैशबोर्ड पर जाएं",
    "payment.success.securityTitle": "सुरक्षित लेन-देन",
    "payment.success.securityDescription": "आपका भुगतान Stripe के माध्यम से सुरक्षित रूप से संसाधित किया गया है। आपको जल्द ही एक पुष्टिकरण ईमेल प्राप्त होगा।",
    "payment.success.needHelp": "शुरू करने में मदद चाहिए?",
    "payment.success.contactSupport": "सहायता से संपर्क करें",

    // Breakdown Page
    "breakdown.analysisTailored": "के लिए अनुकूलित विश्लेषण:",
    "breakdown.stateSpecificRules": "राज्य-विशिष्ट लीज़ नियम और सुझाव",
    "breakdown.securityDepositLimit": "सुरक्षा जमा सीमा",
    "breakdown.lateFeeLimit": "देर शुल्क सीमा",
    "breakdown.noticePeriod": "सूचना अवधि",
    "breakdown.requiredDisclosures": "आवश्यक प्रकटीकरण",
    "breakdown.tip": "सुझाव",
    "breakdown.backToSummary": "सारांश पर वापस जाएं",
    "breakdown.leaseEasy": "Conmates",
    "breakdown.conmates": "Conmates",
  },
  ar: {
    // Arabic translations
    "nav.home": "الرئيسية",
    "nav.upload": "رفع الإيجار",
    "nav.community": "المجتمع",
    "nav.resources": "الموارد",
    "nav.payment": "الدفع",
    "nav.alerts": "التنبيهات",
    "nav.support": "الدعم",
    "home.payment": "الدفع",
    
    // Payment page translations (already in English section, but adding here for completeness)
    "payment.completeYourPurchase": "أكمل عملية الشراء",
    "payment.securePayment": "دفع آمن",
    "payment.leaseAnalysis": "تحليل الإيجار",
    "payment.instantAccess": "وصول فوري",
    "payment.oneTimePayment": "دفعة واحدة",
    "payment.whatsIncluded": "ما هو مشمول",
    "payment.aiAnalysis": "تحليل الإيجار بالذكاء الاصطناعي",
    "payment.clauseBreakdown": "تحليل بند ببند",
    "payment.redFlagDetection": "كشف العلامات الحمراء",
    "payment.pdfReport": "تحميل تقرير PDF",
    "payment.communityAccess": "الوصول للمجتمع",
    "payment.emailAddress": "عنوان البريد الإلكتروني",
    "payment.enterEmail": "أدخل بريدك الإلكتروني",
    "payment.fullName": "الاسم الكامل",
    "payment.enterName": "أدخل اسمك الكامل",
    "payment.processing": "جاري المعالجة...",
    "payment.payNow": "ادفع الآن",
    "payment.stripeSecurity": "دفعك آمن، ولا نخزن بياناتك المالية أبداً. جميع المعاملات تتم من خلال خوادم Stripe الآمنة.",
    "payment.moneyBackGuarantee": "ضمان استرداد الأموال لمدة 30 يوماً",
    "payment.guaranteeDescription": "غير راضٍ؟ احصل على استرداد كامل خلال 30 يوماً، بدون أسئلة.",

    // Payment success page translations
    "payment.success.title": "تم الدفع بنجاح!",
    "payment.success.description": "شكراً لك على الشراء. لديك الآن إمكانية الوصول لجميع ميزات Conmates.",
    "payment.success.orderDetails": "تفاصيل الطلب",
    "payment.success.product": "المنتج",
    "payment.success.amount": "المبلغ",
    "payment.success.status": "الحالة",
    "payment.success.paid": "مدفوع",
    "payment.success.transactionId": "معرف المعاملة",
    "payment.success.nextSteps": "الخطوات التالية",
    "payment.success.step1.title": "ارفع عقد الإيجار",
    "payment.success.step1.description": "اذهب لصفحة الرفع وقدم وثيقة الإيجار للتحليل.",
    "payment.success.step2.title": "احصل على تحليلك",
    "payment.success.step2.description": "احصل على تحليل شامل لشروط وأحكام إيجارك.",
    "payment.success.step3.title": "حمل التقرير",
    "payment.success.step3.description": "حمل تقرير PDF المفصل للرجوع إليه مستقبلاً.",
    "payment.success.uploadLease": "رفع الإيجار",
    "payment.success.goToDashboard": "اذهب للوحة التحكم",
    "payment.success.securityTitle": "معاملة آمنة",
    "payment.success.securityDescription": "تمت معالجة دفعتك بأمان من خلال Stripe. ستصلك رسالة تأكيد قريباً.",
    "payment.success.needHelp": "تحتاج مساعدة للبدء؟",
    "payment.success.contactSupport": "تواصل مع الدعم",

    // Breakdown Page
    "breakdown.analysisTailored": "تحليل مخصص لـ:",
    "breakdown.stateSpecificRules": "قواعد الإيجار الخاصة بالولاية والنصائح",
    "breakdown.securityDepositLimit": "حد الإيداع الأمني",
    "breakdown.lateFeeLimit": "حد الرسوم المتأخرة",
    "breakdown.noticePeriod": "فترة الإشعار",
    "breakdown.requiredDisclosures": "الإفصاحات المطلوبة",
    "breakdown.tip": "نصيحة",
    "breakdown.backToSummary": "العودة إلى الملخص",
    "breakdown.leaseEasy": "Conmates",
    "breakdown.conmates": "Conmates",
  },
}

// After the translations object definition, ensure all keys in 'en' exist in 'es', 'zh', 'hi', and 'ar'.
Object.keys(translations.en).forEach((key) => {
  ["es", "zh", "hi", "ar"].forEach((lang) => {
    const typedLang = lang as "en" | "es" | "zh" | "hi" | "ar";
    if (!(key in translations[typedLang])) {
      translations[typedLang][key] = translations.en[key];
    }
  });
});

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  useEffect(() => {
    const savedLanguage = localStorage.getItem("leaseasy-language") as Language
    if (savedLanguage && translations[savedLanguage]) {
      setLanguage(savedLanguage)
    }
  }, [])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem("leaseasy-language", lang)
    document.documentElement.dir = "ltr"
    document.documentElement.lang = lang
  }

  const t = (key: string): string => {
    // Fallback to English if the current language or key is missing
    return (
      (translations[language] && translations[language][key as keyof (typeof translations)[typeof language]]) ||
      translations["en"][key as keyof (typeof translations)["en"]] ||
      key
    )
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
